#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n'

main() {

    git fetch --prune
    git checkout master
    git pull
    git branch --merged | { egrep -v "(^\*|master|dev)" || true; } | xargs git branch -d
}

main

